### ISSUE TITLE
it dose not vector drawable 

### ISSUE THREAD

**Issue by a-najar** [techery/ProperRatingBar#29]
android.view.InflateException: Binary XML file line #79: Error inflating class io.techery.properratingbar.ProperRatingBar
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)

**Comment by brittonjg** [comment]
It would be good to fix this. I could always create a PR to sort out the issue. I am pretty sure it is a cause of updating the build.gradle file and ProperRatingBar.java to use the ContextCompat.getDrawable. Should do the trick.
